# publish-nuget.yml
name: Build, Test, and Publish NuGet
description: Build, test, package, and publish NuGet package based on project & solution including NuGet Feed as input

inputs:
  nuget-feed-url:
    description: "NuGet Feed to publish to, defaults to https://{{ github.repository_owner }}/index.json"
    required: false
    default: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

  nuget-feed-name:
    description: "Name of NuGet feed, defaults to github"
    required: false
    default: github

  config:
    description: "Build configuration to use, defaults to Release"
    required: false
    default: Release

  version:
    description: "Version for this package"
    required: true

  project-path:
    description: "Path to the project to package. Used in dotnet pack"
    required: true

  solution-path:
    description: "Path to the solution to restore, test, and build. Used indotnet restore, build, and test."
    required: true

  nuget-feed-password:
    description: "Password for NuGet Feed authentication & api key for pushing."
    required: true

  nuget-feed-user:
    description: "Username for NuGet Feed authentication. Defaults to {{ github.repository_owner }}."
    required: false
    default: ${{ github.repository_owner }}

  output-path:
    description: "Path for outputs to be published to. Defaults to {{ github.workspace }}/out"
    required: false
    default: ${{ github.workspace }}/out

runs:
  using: "composite"
  steps:
    - name: Add Custom NuGet Feed to .NET
      run: dotnet nuget add source ${{ inputs.nuget-feed-url }} -n ${{ inputs.nuget-feed-name }} -u ${{ inputs.nuget-feed-user }} -p ${{ inputs.nuget-feed-password }} --store-password-in-clear-text
      shell: bash

    - name: Restore dependencies
      run: dotnet restore ${{ inputs.solution-path }}
      shell: bash

    - name: Build
      run: dotnet build ${{ inputs.solution-path }} --no-restore /p:VersionPrefix=${{ inputs.version }} --configuration ${{ inputs.config }} -o ${{ inputs.output-path }}
      shell: bash

    - name: Test
      run: dotnet test ${{ inputs.solution-path }} --no-build --configuration ${{ inputs.config }} /p:OutputPath=${{ inputs.output-path }}
      shell: bash

    - name: Package
      run: dotnet pack ${{ inputs.project-path }} --no-build --configuration ${{ inputs.config }} /p:Version=${{ inputs.version }} /p:OutputPath=${{ inputs.output-path }} -o packages
      shell: bash

    - name: NuGet Push
      run: |
        dotnet nuget push packages/*.nupkg --source ${{ inputs.nuget-feed-url }} --skip-duplicate --api-key ${{ inputs.nuget-feed-password }}
      shell: bash
